#ifndef DDL_CONFIG_H
#define DDL_CONFIG_H

typedef enum eDDLModules
{
    eDDL_MODULE_DISTANCE,
    eDDL_MODULE_SERVO,
    eDDL_MODULE_TEMPERATURE_HUMIDITY,
    eDDL_MODULE_GPS,
    eDDL_MODULE_COMPASS,
    eDLL_MODULE_COUNT
} eDDLModules;

#endif