#ifndef DDL_SCHEDULER_CONFIG_H
#define DDL_SCHEDULER_CONFIG_H 

typedef enum eSchedulerConfig
{
    eSCHEDULER_QUEUE_CAPACITY  = 4,
    eSCHEDULER_CYCLE_TIME_MS   = 2000,
    eSCHEDULER_SUBSCRIBERS_MAX = 8,
    eSCHEDULER_TICK_MS = eSCHEDULER_CYCLE_TIME_MS / eSCHEDULER_SUBSCRIBERS_MAX
} eSchedulerConfig;

#endif